### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by Hedronmx** [faejr/valawarden#16]
Sorry for the simple question, but I want to use this app and I can't login with my bit warden credentials

**Comment by faejr** [comment]
The application itself is still in pretty early stages. However logging in should definitely work. Do you not get any errors?

**Comment by Hedronmx** [comment]
Just tells me that my credentials are wrong, I am 100% certain they are right since I can log into the official vault of Bitwarden. Should I change the base url?

**Comment by faejr** [comment]
That's definitely strange, are you using the latest tagged release or the latest develop? There may be something wrong in the tagged released (0.1.0)

**Comment by Hedronmx** [comment]
I followed the building instructions on the read me file. Cloned the repo and installed using the sh file

**Comment by Hedronmx** [comment]
I really want to use this app. seems pretty dang cool.

**Comment by faejr** [comment]
Excuse my absence, life has been very busy the past weeks unfortunately.

Have you tried running the application through the terminal? `./app run`

This should give some better insight to why it doesn't work

**Comment by faejr** [comment]
Also please check how many kdf iterations your key uses (under security in bitwarden)

Currently the application is hardcoded to 5000 iterations (old standard) and I need to add a check for the amount of iterations

**Comment by Hedronmx** [comment]
Kdf interations was the solution. Changed it to 5000

**Comment by faejr** [comment]
@Hedronmx Glad to hear that resolved it! I'll be implementing the pre-login functionality as soon as I have time and of course with that go into general improvements :)
