### ISSUE TITLE
Icon/Logo

### ISSUE THREAD

**Issue by faejr** [faejr/valawarden#8]
An icon or logo should be created to properly distinguish the application

**Comment by richardbmx** [comment]
@LiljebergXYZ  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by faejr** [comment]
Heya @richardbmx that actually sounds lovely, are you familiar with Bitwarden or elementary and their human interface guidelines, or are you just interested in contributing for the fun of it?

I just threw together something basic myself today, but alas I am not a graphics designer and it's rather basic, and is more meant to be kept temporary either way :)

**Comment by richardbmx** [comment]
@LiljebergXYZ  Hi, I would like to present my proposal, it is based on identifying security and thus show at first glance the relationship of your project with the security of the user. As you can see it integrates very well in different colors. I hope you like it if you want some change you just have to ask for it.

![presentacion](https://user-images.githubusercontent.com/35604837/47973519-3cc5df00-e07b-11e8-8d78-3354d224abac.png)

**Comment by faejr** [comment]
@richardbmx That looks absolutely great and definitely conveys the message! I'm just thinking about how to adhere to and follow the `human interface guidelines` and turn this into an icon as well :)

What license would to be handing this to the product with and how would you like to be attributed and so on?

Edit: I also love the variation on color scheme!

**Comment by richardbmx** [comment]
@LiljebergXYZ  Some versions in ICON and FAVICON format

![icon](https://user-images.githubusercontent.com/35604837/48022503-ab557c00-e111-11e8-9f61-3d68b6d9f1a0.png)

**Comment by faejr** [comment]
@richardbmx Wow these are looking so great! This will definitely put the edge to the project that I would like!

Do you have any thoughts on licensing/attribution yet? If you feel it is final feel free to submit a PR with the logo :)

**Comment by richardbmx** [comment]
@LiljebergXYZ Here you can find a Google folder with all the necessary files to use the logo, find different variations in different formats and also open a file that grants all the rights for free use.

[Google Dirve](https://drive.google.com/open?id=14uZfP9qW_tp3OPI9TbDfZpu8RPLUmOtJ)

**Comment by faejr** [comment]
Closed thanks to #12

**Comment by richardbmx** [comment]
Hello I have modified the text of the logo I would like you to see the change in this way it looks much better, I will make the pull resques with the changes
![logotype96](https://user-images.githubusercontent.com/35604837/48240975-4fa61f80-e3ab-11e8-8d59-9908d3be18dd.png)

**Comment by richardbmx** [comment]
@LiljebergXYZ  I am trying to make the changes but I see that you do it in a very different way since it is inside the application, I leave the google folder with the changes so you can do it

[Google Drive](https://drive.google.com/open?id=14uZfP9qW_tp3OPI9TbDfZpu8RPLUmOtJ)
